version: "3"
services:
  caddy:
    image: abiosoft/caddy
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    volumes: 
      - ./Caddyfile:/etc/Caddyfile
    environment:
      - ACME_AGREE=true
  webserver:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: "./api/Dockerfile"
    # labels:
    #   - "virtual.host=api.retrylife.ca"  # your domains separated with a space
    #   - "virtual.port=5000"  # exposed port of this container
    #   - "virtual.tls-email=ewpratten@gmail.com"  # ssl is now on
    #   - "virtual.websockets" # enable websocket passthrough