version: "3"
services:
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  # needs socket to read events
      - ./certs/acme:/etc/caddy/acme  # to save acme
      - ./certs/ocsp:/etc/caddy/ocsp  # to save certificates
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webserver
    command: "echo 'cors' >> /etc/caddy/Caddyfile"
  webserver:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: "./app/Dockerfile"
    labels:
      - "virtual.host=api.retrylife.ca"  # your domains separated with a space
      - "virtual.port=5000"  # exposed port of this container
      - "virtual.tls-email=ewpratten@gmail.com"  # ssl is now on
      - "virtual.websockets" # enable websocket passthrough